---
- name: Update CentOS and Ubuntu systems
  hosts: test
  become: yes  # This allows Ansible to use sudo or become user

  tasks:
    - name: Update CentOS packages
      when: "'CentOS' in ansible_distribution"
      yum:
        name: '*'
        state: latest
      register: centos_update_result

    - name: Update Ubuntu packages
      when: "'Ubuntu' in ansible_distribution"
      apt:
        update_cache: yes
        upgrade: dist
      register: ubuntu_update_result

    - name: Save logs to a file
      copy:
        content: |
          CentOS Update Log:
          {{ centos_update_result | to_nice_json }}

          Ubuntu Update Log:
          {{ ubuntu_update_result | to_nice_json }}
        dest: /var/logs/update_logs.txt
      delegate_to: localhost
